# Generated by Django 4.2.1 on 2023-05-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
