# Generated by Django 4.2.1 on 2023-05-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0002_alter_advocate_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
